- .github/workflows/ci.yaml
- .gitignore
- e2e/npm-links/BUILD.bazel
- e2e/npm-links/WORKSPACE
- e2e/npm-links/consumer/BUILD.bazel
- e2e/npm-links/consumer/src/consumer.js
- e2e/npm-links/consumer/src/spec.js
- e2e/npm-links/lib/BUILD.bazel
- e2e/npm-links/lib/src/lib.js
- e2e/npm-links/main.js
- e2e/npm-links/package.json
- e2e/npm-links/pnpm-lock.yaml
Add `npm-links` sample to describe how to use `esbuild` rule with `npm_link_package` rule. The sample is based on @jbedard 's sample https://github.com/jbedard/rules_esbuild/tree/npm-link-package/e2e/npm-links
> add npm-links sample

- esbuild/private/versions.bzl
ESBuild has fixes in the latest version, specifically fixes for handling Typescript decorators that we would like to use. Requesting that the latest, 0.14.51 be added to the supported list of versions for `rules_esbuild`.
Used the `scripts/mirror_release.sh` to create the block.
> Support esbuild 0.14.51

- esbuild/private/esbuild.bzl
- examples/banner/BUILD.bazel
- examples/css/BUILD.bazel
Don't preserve symlinks since doing so breaks node_modules resolution in the pnpm-style symlinked node_modules structure. See https://pnpm.io/symlinked-node-modules-structure.
NB: esbuild will currently leave the sandbox and end up in the output tree until symlink guards are created to prevent this. See https://github.com/aspect-build/rules_esbuild/pull/32.
> fix: don't preserve symlinks so we can resolve npm deps in the symlinked node_modules tree

- internal_deps.bzl
This is from the https://github.com/bazel-contrib/rules-template template but we don't seem to use it.
>  chore(deps): remove bazel-integration-testing 

- esbuild/private/toolchains_repo.bzl
- esbuild/private/versions.bzl
- esbuild/repositories.bzl
- scripts/mirror_release.sh
They changed the platform naming and URL structure so now we have to be conditional on the version in some spots
> chore: mirror latest esbuild version

- esbuild/private/launcher.js
Looks like tsconfig was set in the old rules_nodejs [@bazel/esbuild](https://github.com/bazelbuild/rules_nodejs/blob/c18bc5f4208764fcdaa160f88d072bf33fef53b2/packages/esbuild/esbuild.bzl#L134) version of this rule (for path mappings) but it is no longer load bearing in rules_esbuild.
See https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1678478456514209 for more context.
> fix: don't ignore tsconfig field on user config

- BUILD.bazel
- MODULE.bazel
- esbuild/dependencies.bzl
- internal_deps.bzl
The gazelle plugin is now a separate module
> chore: bump skylib to latest

- docs/rules.md
- esbuild/defs.bzl
This is another one that has to keep getting fixed manually after docsite generation
> chore: fix link esbuild macro docstring

- examples/define/BUILD.bazel
- examples/define/bundle_production.expected
- examples/define/main.js
Wrote this to debug something and seems worth adding...
> test: add esbuild(define) tests

- e2e/npm-links/WORKSPACE
- e2e/smoke/WORKSPACE.bazel
- e2e/sourcemaps/WORKSPACE
- esbuild/repositories.bzl
See https://github.com/aspect-build/rules_js/issues/817
BREAKING CHANGE: rename LATEST_VERSION to LATEST_ESBUILD_VERSION
> fix: rename LATEST_VERSION to LATEST_ESBUILD_VERSION

- MODULE.bazel
- e2e/npm-links/MODULE.bazel
- esbuild/dependencies.bzl
Windows fix. BCR should be green now for Windows with this change.
---
- Chore (any other change that doesn't affect source or test files, such as configuration)
- Covered by existing test cases
> chore: bump rules_js dep to 1.29.2 to pickup Windows fix

- esbuild/private/toolchains_repo.bzl
I think @gregmagolan introduced a mistake in https://github.com/aspect-build/rules_esbuild/commit/abf0528384474f3b59733594e1f644b214c2a0ff#diff-31aeb5f9afff8dfdbee6cfca655d03053a3ffaf8857a1774f620b5e61daaa3a9L64-R64 and we don't have any CI testing for use of older versions of esbuild. I did this again from reasoning based on first-principles about what mapping we need to do here.
- Bug fix (change which fixes an issue)
- Covered by existing test cases
With this branch named to trigger tests
> fix: correct mapping to earlier esbuild releases

- esbuild/private/esbuild.bzl
This ensures that folks know that `config` is the replacement for `args` when coming from `@bazel/esbuild`. This is an issue I hit, see this discussion in slack https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1675462695407799?thread_ts=1674525810.470589&cid=CEZUUKQ6P
CC @mattem @gregmagolan
> docs: note args --> config migration

- esbuild/extensions.bzl
- esbuild/repositories.bzl
Fixes the problem where overriding the default esbuild version in MODULE.bazel results in the error `Multiple conflicting toolchains declared for name esbuild`.
The solution is an adapted copy of @kormide's [fix to a similar problem under rules_nodejs](https://github.com/bazelbuild/rules_nodejs/pull/3626).
> fix: allow root repositories to override esbuild toolchain version under bzlmod

- BUILD.bazel
- CONTRIBUTING.md
- MODULE.bazel
- WORKSPACE
- internal_deps.bzl
We don't have any Go sources in rules_esbuild so there's no reason we should install a Go toolchain or worry about upgrading it. 'aspect configure' provides the auto-generation for bzl_library targets so we don't need Gazelle either.
> chore: remove Go

- .aspect/bazelrc/.gitignore
- .bazelignore
- .bazelrc
- .github/workflows/BUILD.bazel
- .github/workflows/ci.bazelrc
- .github/workflows/ci.yaml
- .github/workflows/release.yml
- .gitignore
- .npmrc
- WORKSPACE
- docs/BUILD.bazel
- e2e/bundle/.bazelrc
- e2e/bundle/.bazelversion
- e2e/bundle/.npmrc
- e2e/npm-links/.bazelignore
- e2e/npm-links/.bazelrc
- e2e/npm-links/.npmrc
- e2e/npm-links/MODULE.bazel
- e2e/npm-links/WORKSPACE
- e2e/smoke/.bazelrc
- e2e/smoke/.npmrc
- e2e/sourcemaps/.bazelrc
- e2e/sourcemaps/.bazelversion
- e2e/sourcemaps/.npmrc
- e2e/tsconfig/.bazelrc
- e2e/tsconfig/.npmrc
Lots of cleanup of our CI and bazelrc patterns here. Aligns these patterns with the other rules_js rulesets. No functional changes.
> chore: align ci yaml pattern

- MODULE.bazel
- e2e/bundle/MODULE.bazel
- e2e/tsconfig/MODULE.bazel
- esbuild/dependencies.bzl
bazel-lib 2.7.3 has a bad URL in coreutils for darwin x86
> chore: bump miminum dep to aspect_bazel_lib 2.7.6

- MODULE.bazel
- e2e/bundle/MODULE.bazel
- e2e/npm-links/MODULE.bazel
- e2e/tsconfig/MODULE.bazel
- esbuild/dependencies.bzl
aspect_bazel_lib min bump goes along with rules_js bump in https://github.com/aspect-build/rules_js/pull/1763 to pick up fix for copy_to_directory that affects npm_package: https://github.com/aspect-build/bazel-lib/pull/857.
> chore: bump to rules_js 2.0.0-rc1 and minimum aspect_bazel_lib 2.7.7

- esbuild/private/plugins/bazel-sandbox.js
This module cache came up as problematic with the presence of multiple versions of a package in a given dependency closure. In our case, we have `minipass` 4.2.8 and 7.0.4 (required by `glob` 9.3.2 and `path-scurry` 1.10.1 respectively) in a given closure. These are strictly not compatible with each other, so resolving `minipass` from `glob` should yield 4.2.8 and from `path-scurry` should yield 7.0.4. The module cache however results in everything getting the same version, as we are keying only by name sans version.
Log output I added to illustrate the point:
```
DEBUG NOAH BEGIN: 
IMPORTER /home/noah/.cache/bazel/_bazel_noah/8fd1d20666a46767e7f29541678514a0/sandbox/linux-sandbox/10/execroot/__main__/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/glob@9.3.2/node_modules/glob/dis …
```
> fix: remove module cache in sandbox plugin

- MODULE.bazel
- esbuild/dependencies.bzl
Ensures users pick up https://github.com/bazelbuild/rules_nodejs/pull/3760 fix which is a footgun that should be avoided.
> chore: bump minimum rules_nodejs to 6.2.0
